import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/api/supabaseClient";
import { downloadContractPDF } from "@/lib/contractExport";
import { generateContractSections } from "@/lib/contractSections";
import ContractSectionsList from "@/components/contract/ContractSectionsList";
import RelistButton from "@/components/vehicles/RelistButton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  ArrowLeft, FileText, Car, Truck, Download, AlertCircle, Loader2, X, PenLine,
} from "lucide-react";

/* ─── Helpers ────────────────────────────────────────────────────────────── */

function formatDate(iso) {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-ZA", {
    day: "2-digit", month: "short", year: "numeric",
  });
}

function vehicleImage(images) {
  if (!images) return null;
  if (Array.isArray(images)) return images[0] ?? null;
  if (typeof images === "string") {
    try {
      const parsed = JSON.parse(images);
      return Array.isArray(parsed) ? parsed[0] : parsed;
    } catch {
      return images;
    }
  }
  return null;
}

function StatusBadge({ status }) {
  const map = {
    active:    "bg-green-100 text-green-700",
    approved:  "bg-green-100 text-green-700",
    pending:   "bg-yellow-100 text-yellow-700",
    signed:    "bg-blue-100 text-blue-700",
    completed: "bg-gray-100 text-gray-600",
    cancelled: "bg-red-100 text-red-600",
    rejected:  "bg-red-100 text-red-600",
    available: "bg-blue-100 text-blue-700",
    rented:    "bg-purple-100 text-purple-700",
  };
  const cls = map[status?.toLowerCase()] ?? "bg-gray-100 text-gray-600";
  return (
    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium capitalize ${cls}`}>
      {status ?? "unknown"}
    </span>
  );
}

function Empty({ message }) {
  return (
    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground gap-3">
      <AlertCircle className="w-10 h-10 opacity-40" />
      <p className="text-sm text-center">{message}</p>
    </div>
  );
}

function Spinner() {
  return (
    <div className="flex items-center justify-center py-16">
      <Loader2 className="w-8 h-8 animate-spin text-primary opacity-60" />
    </div>
  );
}

/* ─── Contract download ──────────────────────────────────────────────────── */

async function downloadContract(rental) {
  const v = rental.vehicles ?? {};
  const vehicleInfo = [v.make, v.model, v.year ? `(${v.year})` : ''].filter(Boolean).join(' ');
  const text = rental.contract_text || [
    "VEHICLE RENTAL AGREEMENT",
    "=".repeat(40),
    "",
    `Rental ID:   ${rental.id}`,
    `Status:      ${rental.status ?? "—"}`,
    `Start Date:  ${formatDate(rental.start_date)}`,
    `End Date:    ${formatDate(rental.end_date)}`,
    `Price/Week:  R ${rental.price_per_week ?? "—"}`,
    `Deposit:     R ${rental.deposit ?? "—"}`,
    "",
    "VEHICLE",
    "-".repeat(20),
    `Make/Model:  ${v.make ?? ""} ${v.model ?? "—"}`,
    `Plate:       ${v.plate ?? "—"}`,
    `Type:        ${v.type ?? "—"}`,
    "",
    "=".repeat(40),
    "Generated by Skootlink (Pty) Ltd.",
    "www.skootlink.co.za | help@skootlink.co.za",
  ].join("\n");

  try {
    await downloadContractPDF(text, rental.id, vehicleInfo);
  } catch (err) {
    console.error('[MyBriefcase] PDF download failed:', err);
    toast.error('Could not download the contract. Please try again.');
  }
}

/* ─── Contracts tab ──────────────────────────────────────────────────────── */

function ContractsTab({ userId, role }) {
  const [items, setItems]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    if (!userId) { setLoading(false); return; }
    (async () => {
      try {
        setLoading(true);

        let query = supabase
          .from("rentals")
          .select(`
            id, status, start_date, end_date,
            price_per_week, deposit, contract_text, created_at,
            owner_id, driver_id,
            vehicles ( make, model, plate, type, images )
          `)
          .not("contract_text", "is", null)
          .order("created_at", { ascending: false });

        // For 'both' role, fetch contracts where user is either owner OR driver.
        // For single roles, filter by the relevant column only.
        if (role === "both") {
          query = query.or(`owner_id.eq.${userId},driver_id.eq.${userId}`);
        } else if (role === "owner") {
          query = query.eq("owner_id", userId);
        } else {
          query = query.eq("driver_id", userId);
        }

        const { data, error: err } = await query;
        if (err) throw err;
        setItems(data ?? []);
      } catch (err) {
        console.error("ContractsTab:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    })();
  }, [userId, role]);

  if (loading) return <Spinner />;
  if (error)   return <Empty message={`Could not load contracts: ${error}`} />;
  if (!items.length) return <Empty message="No contracts yet." />;

  return (
    <div className="space-y-3">
      {items.map((r) => {
        const v   = r.vehicles ?? {};
        const img = vehicleImage(v.images);
        return (
          <Card key={r.id} className="border border-border shadow-sm overflow-hidden">
            {img && (
              <img src={img} alt={`${v.make} ${v.model}`}
                className="w-full h-32 object-cover" />
            )}
            <CardContent className="pt-4 pb-3 px-4">
              <div className="flex items-start justify-between gap-3">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <FileText className="w-4 h-4 text-primary flex-shrink-0" />
                    <span className="font-medium text-sm truncate">Rental #{r.id}</span>
                    <StatusBadge status={r.status} />
                  </div>
                  {(v.make || v.model) && (
                    <p className="text-xs text-muted-foreground">
                      {v.make ?? ""} {v.model ?? ""}{v.plate ? ` · ${v.plate}` : ""}
                    </p>
                  )}
                  <p className="text-xs text-muted-foreground mt-0.5">
                    {formatDate(r.start_date)} → {formatDate(r.end_date)}
                  </p>
                  {r.price_per_week && (
                    <p className="text-xs font-semibold text-primary mt-1">
                      R {r.price_per_week}/week
                    </p>
                  )}
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  className="flex-shrink-0 gap-1.5 text-xs"
                  onClick={() => downloadContract(r)}
                >
                  <Download className="w-3.5 h-3.5" />
                  PDF
                </Button>
              </div>
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

/* ─── Active Rentals (driver) ────────────────────────────────────────────── */

function ActiveRentalsTab({ userId }) {
  const [items, setItems]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    if (!userId) { setLoading(false); return; }
    (async () => {
      try {
        setLoading(true);
        const { data, error: err } = await supabase
          .from("rentals")
          .select(`
            id, status, start_date, end_date, price_per_week,
            vehicles ( make, model, plate, type, images, location )
          `)
          .eq("driver_id", userId)
          .eq("status", "active")
          .order("start_date", { ascending: true });

        if (err) throw err;
        setItems(data ?? []);
      } catch (err) {
        console.error("ActiveRentalsTab:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    })();
  }, [userId]);

  if (loading) return <Spinner />;
  if (error)   return <Empty message={`Could not load rentals: ${error}`} />;
  if (!items.length) return <Empty message="No active rentals right now." />;

  return (
    <div className="space-y-3">
      {items.map((r) => {
        const v   = r.vehicles ?? {};
        const img = vehicleImage(v.images);
        return (
          <Card key={r.id} className="border border-border shadow-sm overflow-hidden">
            {img && (
              <img src={img} alt={`${v.make} ${v.model}`}
                className="w-full h-32 object-cover" />
            )}
            <CardContent className="pt-3 pb-3 px-4">
              <div className="flex items-center gap-2 mb-1">
                <Car className="w-4 h-4 text-primary flex-shrink-0" />
                <span className="font-medium text-sm">
                  {v.make ?? ""} {v.model ?? "Vehicle"}
                </span>
                <StatusBadge status={r.status} />
              </div>
              {v.plate    && <p className="text-xs text-muted-foreground">{v.plate}</p>}
              {v.type     && <p className="text-xs text-muted-foreground capitalize">{v.type}</p>}
              {v.location && <p className="text-xs text-muted-foreground">📍 {v.location}</p>}
              <p className="text-xs text-muted-foreground mt-0.5">
                {formatDate(r.start_date)} → {formatDate(r.end_date)}
              </p>
              {r.price_per_week && (
                <p className="text-xs font-semibold text-primary mt-1">
                  R {r.price_per_week}/week
                </p>
              )}
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

/* ─── Active Assignments (owner) ─────────────────────────────────────────── */

function ActiveAssignmentsTab({ userId }) {
  const [items, setItems]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);

  useEffect(() => {
    if (!userId) { setLoading(false); return; }
    (async () => {
      try {
        setLoading(true);
        const { data, error: err } = await supabase
          .from("rentals")
          .select(`
            id, status, start_date, end_date, price_per_week,
            vehicles ( make, model, plate, type, images, location )
          `)
          .eq("owner_id", userId)
          .eq("status", "active")
          .order("start_date", { ascending: true });

        if (err) throw err;

        const driverIds = [...new Set((data ?? []).map(r => r.driver_id).filter(Boolean))];
        let profileMap  = {};
        if (driverIds.length) {
          const { data: profiles } = await supabase
            .from("profiles")
            .select("id, full_name, phone")
            .in("id", driverIds);
          (profiles ?? []).forEach(p => { profileMap[p.id] = p; });
        }

        setItems((data ?? []).map(r => ({ ...r, driverProfile: profileMap[r.driver_id] ?? null })));
      } catch (err) {
        console.error("ActiveAssignmentsTab:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    })();
  }, [userId]);

  if (loading) return <Spinner />;
  if (error)   return <Empty message={`Could not load assignments: ${error}`} />;
  if (!items.length) return <Empty message="No vehicles currently out on assignment." />;

  return (
    <div className="space-y-3">
      {items.map((a) => {
        const v      = a.vehicles ?? {};
        const driver = a.driverProfile ?? {};
        const img    = vehicleImage(v.images);
        return (
          <Card key={a.id} className="border border-border shadow-sm overflow-hidden">
            {img && (
              <img src={img} alt={`${v.make} ${v.model}`}
                className="w-full h-32 object-cover" />
            )}
            <CardContent className="pt-3 pb-3 px-4">
              <div className="flex items-center gap-2 mb-1">
                <Truck className="w-4 h-4 text-primary flex-shrink-0" />
                <span className="font-medium text-sm">
                  {v.make ?? ""} {v.model ?? "Vehicle"}
                </span>
                <StatusBadge status={a.status} />
              </div>
              {v.plate && <p className="text-xs text-muted-foreground">{v.plate}</p>}
              {v.type  && <p className="text-xs text-muted-foreground capitalize">{v.type}</p>}
              <p className="text-xs text-muted-foreground mt-0.5">
                {formatDate(a.start_date)} → {formatDate(a.end_date)}
              </p>
              {a.price_per_week && (
                <p className="text-xs font-semibold text-primary mt-1">
                  R {a.price_per_week}/week
                </p>
              )}
              {driver.full_name && (
                <p className="text-xs text-muted-foreground mt-1">
                  Driver: {driver.full_name}{driver.phone ? ` · ${driver.phone}` : ""}
                </p>
              )}
            </CardContent>
          </Card>
        );
      })}
    </div>
  );
}

/* ─── Prepare Contract modal (owner, per-vehicle draft) ──────────────────── */

function PrepareContractModal({ vehicle, ownerId, onClose }) {
  const [sections, setSections] = useState([]);
  const [loading, setLoading]   = useState(true);
  const [saving, setSaving]     = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const { data: { user: authUser } } = await supabase.auth.getUser();
        const { data: ownerProfile } = await supabase
          .from('profiles')
          .select('full_name, id_number, passport_number')
          .eq('id', ownerId)
          .single();

        // Use the saved draft if one already exists for this vehicle,
        // otherwise generate fresh — pre-filled with vehicle + owner info,
        // driver fields left blank since there's no driver yet at this
        // stage. vehicle.price stands in as a sensible starting weekly
        // rate; no rental exists yet so there are no real dates to fill.
        if (Array.isArray(vehicle.draft_contract_sections) && vehicle.draft_contract_sections.length > 0) {
          setSections(vehicle.draft_contract_sections);
        } else {
          const fresh = generateContractSections(
            { price_per_week: vehicle.price },
            vehicle,
            null,
            { ...ownerProfile, email: authUser?.email }
          );
          setSections(fresh);
        }
      } catch (err) {
        console.error('[PrepareContractModal] Failed to load:', err);
        toast.error('Could not load the contract draft.');
      } finally {
        setLoading(false);
      }
    })();
  }, [vehicle, ownerId]);

  const handleSaveDraft = async () => {
    setSaving(true);
    try {
      const { error } = await supabase
        .from('vehicles')
        .update({ draft_contract_sections: sections })
        .eq('id', vehicle.id);
      if (error) throw error;
      toast.success('Contract draft saved. It\'ll be ready to send once you find a driver.');
      onClose(sections);
    } catch (err) {
      console.error('[PrepareContractModal] Save failed:', err);
      toast.error('Could not save the draft: ' + err.message);
    } finally {
      setSaving(false);
    }
  };

  return createPortal(
    <div className="fixed inset-0 z-[9999] flex items-start sm:items-center justify-center p-4 pt-8 sm:pt-4 bg-black/40 overflow-y-auto" onClick={() => onClose()}>
      <div className="bg-card rounded-2xl shadow-xl max-w-4xl w-full p-4 sm:p-6 border border-border flex flex-col max-h-[92vh]" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between mb-1 shrink-0">
          <h2 className="text-xl font-bold">Prepare Contract</h2>
          <button onClick={() => onClose()} className="text-muted-foreground hover:text-foreground"><X className="w-5 h-5" /></button>
        </div>
        <p className="text-xs text-muted-foreground mb-3 shrink-0">
          Draft and customise the rental contract for {vehicle.make} {vehicle.model} in advance. Driver details fill in automatically once you send it to a driver — this saves your wording and structure for that moment.
        </p>

        <div className="rounded-xl p-2 sm:p-3 flex-1 overflow-y-auto mb-4 min-h-0 bg-background border-2 border-primary/30 ring-1 ring-primary/10">
          {loading ? (
            <div className="flex justify-center py-16">
              <Loader2 className="w-6 h-6 animate-spin text-primary opacity-60" />
            </div>
          ) : (
            <ContractSectionsList sections={sections} onChange={setSections} />
          )}
        </div>

        <div className="flex gap-3 shrink-0">
          <Button variant="outline" className="flex-1" onClick={() => onClose()}>Cancel</Button>
          <Button className="flex-1 gap-2" disabled={loading || saving} onClick={handleSaveDraft}>
            {saving ? <><Loader2 className="w-4 h-4 animate-spin" /> Saving…</> : 'Save Draft'}
          </Button>
        </div>
      </div>
    </div>,
    document.body
  );
}

/* ─── My Vehicle Listings (owner) ────────────────────────────────────────── */

function VehicleListingsTab({ userId }) {
  const [items, setItems]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState(null);
  const [contractVehicle, setContractVehicle] = useState(null);

  useEffect(() => {
    if (!userId) { setLoading(false); return; }
    (async () => {
      try {
        setLoading(true);
        const { data, error: err } = await supabase
          .from("vehicles")
          .select("id, make, model, year, plate, type, location, price, status, images, pickup_return_location, expires_at, listing_state, draft_contract_sections")
          .eq("owner_id", userId)
          .order("created_at", { ascending: false });

        if (err) throw err;
        setItems(data ?? []);
      } catch (err) {
        console.error("VehicleListingsTab:", err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    })();
  }, [userId]);

  if (loading) return <Spinner />;
  if (error)   return <Empty message={`Could not load vehicles: ${error}`} />;
  if (!items.length) return (
    <Empty message="You have no vehicle listings yet. Add a vehicle to start earning." />
  );

  return (
    <div className="space-y-3">
      {items.map((v) => {
        const img = vehicleImage(v.images);
        return (
          <Card key={v.id} className="border border-border shadow-sm overflow-hidden">
            {img && (
              <img src={img} alt={`${v.make} ${v.model}`}
                className="w-full h-32 object-cover" />
            )}
            <CardContent className="pt-3 pb-3 px-4">
              <div className="flex items-start justify-between gap-2">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <Car className="w-4 h-4 text-primary flex-shrink-0" />
                    <span className="font-medium text-sm">
                      {v.make ?? ""} {v.model ?? "Vehicle"}
                      {v.year ? ` (${v.year})` : ""}
                    </span>
                  </div>
                  {v.plate    && <p className="text-xs text-muted-foreground">{v.plate}</p>}
                  {v.type     && <p className="text-xs text-muted-foreground capitalize">{v.type}</p>}
                  {v.location && <p className="text-xs text-muted-foreground">📍 {v.location}</p>}
                  {v.price    && (
                    <p className="text-xs font-semibold text-primary mt-1">R {v.price}/week</p>
                  )}
                  {v.expires_at && (() => {
                    const daysLeft = Math.ceil((new Date(v.expires_at) - Date.now()) / (24 * 60 * 60 * 1000));
                    const isExpired = v.listing_state === 'expired';
                    if (isExpired) return (
                      <p className="text-[11px] font-medium text-destructive mt-1">🚫 Hidden from search — re-list to make visible</p>
                    );
                    if (daysLeft <= 7) return (
                      <p className="text-[11px] font-medium text-amber-600 mt-1">
                        ⏰ Expires in {daysLeft} day{daysLeft !== 1 ? 's' : ''}
                      </p>
                    );
                    return null;
                  })()}
                  {(v.listing_state === 'expired' || (v.expires_at && Math.ceil((new Date(v.expires_at) - Date.now()) / (24 * 60 * 60 * 1000)) <= 7)) && (
                    <div className="mt-2">
                      <RelistButton vehicle={v} />
                    </div>
                  )}
                  {Array.isArray(v.draft_contract_sections) && v.draft_contract_sections.length > 0 && (
                    <p className="text-[11px] font-medium text-primary mt-1">📝 Contract draft saved</p>
                  )}
                  <Button
                    size="sm"
                    variant="outline"
                    className="mt-2 gap-1.5 text-xs"
                    onClick={() => setContractVehicle(v)}
                  >
                    <PenLine className="w-3.5 h-3.5" />
                    {Array.isArray(v.draft_contract_sections) && v.draft_contract_sections.length > 0 ? 'Edit Contract Draft' : 'Prepare Contract'}
                  </Button>
                </div>
                <StatusBadge status={v.status ?? "available"} />
              </div>
            </CardContent>
          </Card>
        );
      })}

      {contractVehicle && (
        <PrepareContractModal
          vehicle={contractVehicle}
          ownerId={userId}
          onClose={(savedSections) => {
            // Reflect the just-saved draft immediately in this list, without
            // needing a full refetch, so the "Edit Contract Draft" label and
            // "draft saved" note update right away.
            if (savedSections) {
              setItems(prev => prev.map(item =>
                item.id === contractVehicle.id ? { ...item, draft_contract_sections: savedSections } : item
              ));
            }
            setContractVehicle(null);
          }}
        />
      )}
    </div>
  );
}

/* ─── Main page ──────────────────────────────────────────────────────────── */

export default function MyBriefcase() {
  const navigate = useNavigate();
  const [userId, setUserId]           = useState(null);
  const [role, setRole]               = useState(null);
  const [pageLoading, setPageLoading] = useState(true);

  useEffect(() => {
    let resolved = false;

    const loadProfile = async (uid) => {
      if (!uid) { setRole('driver'); setPageLoading(false); return; }
      try {
        // auth.me() reads account_type from profiles table (source of truth)
        // then falls back to auth user_metadata — covers all user cohorts
        const { data: profile } = await supabase
          .from('profiles')
          .select('account_type, role')
          .eq('id', uid)
          .single();

        const { data: { user: authUser } } = await supabase.auth.getUser();
        const metaType = authUser?.user_metadata?.account_type;
        const resolved = profile?.account_type || profile?.role || metaType || 'driver';

        console.log('[MyBriefcase] account_type:', profile?.account_type, '| role:', profile?.role, '| meta:', metaType, '| resolved:', resolved);

        // Backfill missing account_type so future loads don't need fallback
        if (!profile?.account_type && (profile?.role || metaType)) {
          const fill = profile?.role || metaType;
          supabase.from('profiles').update({ account_type: fill }).eq('id', uid)
            .then(() => console.log('[MyBriefcase] backfilled account_type:', fill));
        }

        setRole(resolved);
      } catch {
        setRole('driver');
      } finally {
        setPageLoading(false);
      }
    };

    // Use onAuthStateChange — reliable on mobile where getSession() may return null
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (resolved) return;
      if (event === 'INITIAL_SESSION' || event === 'SIGNED_IN') {
        resolved = true;
        const uid = session?.user?.id ?? null;
        setUserId(uid);
        loadProfile(uid);
      }
    });

    // Fallback: if onAuthStateChange never fires within 5s
    const fallback = setTimeout(async () => {
      if (resolved) return;
      resolved = true;
      try {
        const { data: { session } } = await supabase.auth.getSession();
        const uid = session?.user?.id ?? null;
        setUserId(uid);
        await loadProfile(uid);
      } catch {
        setRole('driver');
        setPageLoading(false);
      }
    }, 5000);

    return () => {
      clearTimeout(fallback);
      subscription?.unsubscribe();
    };
  }, []);

  if (pageLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-primary opacity-60" />
      </div>
    );
  }

  const isDriver = role === 'driver';
  const isOwner  = role === 'owner';
  const isBoth   = role === 'both';

  const tabs = isBoth
    ? [
        { value: 'rentals',     label: 'My Rentals',  icon: Car,      section: 'Active Rentals',    sub: 'Vehicles you are currently renting' },
        { value: 'listings',    label: 'My Vehicles', icon: Truck,    section: 'My Vehicles',       sub: 'All your listed vehicles' },
        { value: 'assignments', label: 'Assignments', icon: Truck,    section: 'Active Assignments', sub: 'Vehicles currently out on rental' },
        { value: 'contracts',   label: 'Contracts',   icon: FileText, section: 'Contracts',          sub: 'Rentals with a signed contract' },
      ]
    : isOwner
    ? [
        { value: 'listings',    label: 'My Vehicles', icon: Car,      section: 'My Vehicles',       sub: 'All your listed vehicles' },
        { value: 'assignments', label: 'Assignments', icon: Truck,    section: 'Active Assignments', sub: 'Vehicles currently out on rental' },
        { value: 'contracts',   label: 'Contracts',   icon: FileText, section: 'Contracts',          sub: 'Rentals with a signed contract' },
      ]
    : [
        { value: 'rentals',   label: 'Rentals',   icon: Car,      section: 'Active Rentals', sub: 'Vehicles you are currently renting' },
        { value: 'contracts', label: 'Contracts', icon: FileText, section: 'Contracts',       sub: 'Rentals with a signed contract' },
      ];

  const gridCols = tabs.length === 4 ? 'grid-cols-2' : tabs.length === 3 ? 'grid-cols-3' : 'grid-cols-2';

  return (
    <div className="p-4 lg:p-8 max-w-5xl mx-auto pb-20 lg:pb-8">
      {/* Header — back arrow + title, matching SearchPage layout */}
      <div className="flex items-center gap-3 mb-6">
        <button
          onClick={() => { if (window.history.length > 1) navigate(-1); else navigate('/app'); }}
          className="text-muted-foreground hover:text-foreground active:bg-accent rounded-lg p-2 -ml-2"
          style={{ touchAction: 'manipulation', minHeight: '44px' }}
        >
          <ArrowLeft className="w-5 h-5" />
        </button>
        <h1 className="text-2xl font-bold">My Briefcase</h1>
      </div>

      <Tabs defaultValue={tabs[0].value}>
        <TabsList className={`w-full mb-4 h-auto grid ${gridCols} gap-1 bg-muted p-1 rounded-lg`}>
          {tabs.map(({ value, label, icon: Icon }) => (
            <TabsTrigger key={value} value={value} className="text-xs gap-1.5 py-2">
              <Icon className="w-3.5 h-3.5" />
              {label}
            </TabsTrigger>
          ))}
        </TabsList>

        {tabs.map(({ value, section, sub }) => (
          <TabsContent key={value} value={value}>
            <div className="mb-3">
              <h2 className="text-sm font-semibold text-foreground">{section}</h2>
              <p className="text-xs text-muted-foreground">{sub}</p>
            </div>
            {value === "contracts"   && <ContractsTab         userId={userId} role={role} />}
            {value === "rentals"     && <ActiveRentalsTab     userId={userId} />}
            {value === "assignments" && <ActiveAssignmentsTab userId={userId} />}
            {value === "listings"    && <VehicleListingsTab   userId={userId} />}
          </TabsContent>
        ))}
      </Tabs>
    </div>
  );
}
